apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tmc
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./terraform
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tmc-tf-flux