apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: terraform-repo
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/warroyo/tmc-terraform-flux
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tmc
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./terraform
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: terraform-repo
  varsFrom:
  - kind: Secret
    name: tf-tmc-token