---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tf-resources
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 10m0s
  path: flux/terraform-resources
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tmc-tf-flux